# Generated by Django 5.2 on 2025-05-07 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='content_like',
            field=models.ForeignKey(help_text='Введите контент который нравится пользователю', null=True, on_delete=django.db.models.deletion.CASCADE, to='application.content', verbose_name='Контент который нравится пользователю'),
        ),
    ]
