# Generated by Django 5.2 on 2025-05-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_user_content_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='content_like',
        ),
        migrations.AddField(
            model_name='user',
            name='content_like',
            field=models.ManyToManyField(help_text='Введите контент который нравится пользователю', null=True, to='application.content', verbose_name='Контент который нравится пользователю'),
        ),
    ]
