# Generated by Django 5.2 on 2025-05-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_userinteraction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='content_like',
            field=models.ManyToManyField(help_text='Введите контент который нравится пользователю', to='application.content', verbose_name='Контент который нравится пользователю'),
        ),
    ]
